/* eslint-disable @typescript-eslint/no-unused-vars */
/* Test */
export const CardBack: CardObj = {
  suit: "back",
  displayValue: "card",
  value: 0,
  src: "card_back",
};

export const DeckOfCards: CardObj[] = [
  {
    suit: "hearts",
    displayValue: "2",
    value: 2,
    src: "2_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "3",
    value: 3,
    src: "3_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "4",
    value: 4,
    src: "4_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "5",
    value: 5,
    src: "5_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "6",
    value: 6,
    src: "6_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "7",
    value: 7,
    src: "7_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "8",
    value: 8,
    src: "8_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "9",
    value: 9,
    src: "9_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "10",
    value: 10,
    src: "10_of_hearts",
  },
  {
    suit: "hearts",
    displayValue: "J",
    value: 10,
    src: "jack_of_hearts2",
  },
  {
    suit: "hearts",
    displayValue: "Q",
    value: 10,
    src: "queen_of_hearts2",
  },
  {
    suit: "hearts",
    displayValue: "K",
    value: 10,
    src: "king_of_hearts2",
  },
  {
    suit: "hearts",
    displayValue: "A",
    value: 11,
    src: "ace_of_hearts",
  },
  {
    suit: "diamonds",
    displayValue: "2",
    value: 2,
    src: "2_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "3",
    value: 3,
    src: "3_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "4",
    value: 4,
    src: "4_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "5",
    value: 5,
    src: "5_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "6",
    value: 6,
    src: "6_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "7",
    value: 7,
    src: "7_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "8",
    value: 8,
    src: "8_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "9",
    value: 9,
    src: "9_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "10",
    value: 10,
    src: "10_of_diamonds",
  },
  {
    suit: "diamonds",
    displayValue: "J",
    value: 10,
    src: "jack_of_diamonds2",
  },
  {
    suit: "diamonds",
    displayValue: "Q",
    value: 10,
    src: "queen_of_diamonds2",
  },
  {
    suit: "diamonds",
    displayValue: "K",
    value: 10,
    src: "king_of_diamonds2",
  },
  {
    suit: "diamonds",
    displayValue: "A",
    value: 11,
    src: "ace_of_diamonds",
  },
  {
    suit: "clubs",
    displayValue: "2",
    value: 2,
    src: "2_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "3",
    value: 3,
    src: "3_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "4",
    value: 4,
    src: "4_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "5",
    value: 5,
    src: "5_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "6",
    value: 6,
    src: "6_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "7",
    value: 7,
    src: "7_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "8",
    value: 8,
    src: "8_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "9",
    value: 9,
    src: "9_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "10",
    value: 10,
    src: "10_of_clubs",
  },
  {
    suit: "clubs",
    displayValue: "J",
    value: 10,
    src: "jack_of_clubs2",
  },
  {
    suit: "clubs",
    displayValue: "Q",
    value: 10,
    src: "queen_of_clubs2",
  },
  {
    suit: "clubs",
    displayValue: "K",
    value: 10,
    src: "king_of_clubs2",
  },
  {
    suit: "clubs",
    displayValue: "A",
    value: 11,
    src: "ace_of_clubs",
  },
  {
    suit: "spades",
    displayValue: "2",
    value: 2,
    src: "2_of_spades",
  },
  {
    suit: "spades",
    displayValue: "3",
    value: 3,
    src: "3_of_spades",
  },
  {
    suit: "spades",
    displayValue: "4",
    value: 4,
    src: "4_of_spades",
  },
  {
    suit: "spades",
    displayValue: "5",
    value: 5,
    src: "5_of_spades",
  },
  {
    suit: "spades",
    displayValue: "6",
    value: 6,
    src: "6_of_spades",
  },
  {
    suit: "spades",
    displayValue: "7",
    value: 7,
    src: "7_of_spades",
  },
  {
    suit: "spades",
    displayValue: "8",
    value: 8,
    src: "8_of_spades",
  },
  {
    suit: "spades",
    displayValue: "9",
    value: 9,
    src: "9_of_spades",
  },
  {
    suit: "spades",
    displayValue: "10",
    value: 10,
    src: "10_of_spades",
  },
  {
    suit: "spades",
    displayValue: "J",
    value: 10,
    src: "jack_of_spades2",
  },
  {
    suit: "spades",
    displayValue: "Q",
    value: 10,
    src: "queen_of_spades2",
  },
  {
    suit: "spades",
    displayValue: "K",
    value: 10,
    src: "king_of_spades2",
  },
  {
    suit: "spades",
    displayValue: "A",
    value: 11,
    src: "ace_of_spades",
  },
];
